---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=interview-core&var-version=1.0.0-SNAPSHOT
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/interview/interview-core
  labels:
    app: interview-core
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: gubee
  name: interview-core
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: interview-core
      provider: fabric8
      group: gubee
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=interview-core&var-version=1.0.0-SNAPSHOT
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/interview/interview-core
      labels:
        app: interview-core
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: gubee
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gubee/interview
        imagePullPolicy: IfNotPresent
        name: interview-api
        securityContext:
          privileged: false
